-- ── RLS policies for notice_viewers are managed by V19 ──────────────────
-- V19 disables RLS and drops all policies on notice_viewers before converting
-- user_id from UUID to BIGINT. Supabase Realtime is no longer used; notices
-- are delivered via the backend. This migration intentionally does NOT create
-- any policies that depend on auth.uid() (Supabase-specific) so that the
-- schema can be migrated on plain PostgreSQL instances.
