spring:
  application:
    name: cavgomqt
  datasource:
    url: jdbc:postgresql://localhost:5432/cavgomqt
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  web:
    resources:
      add-mappings: false

  jpa:
    hibernate:
      ddl-auto: update
  integration:
    mqtt:
      default-qos: 1
      default-retained: false
      completion-timeout: 5000
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

mqtt:
  client:
    id: cavgomqt
  username: genoyves
  password: Cadio*11.
  broker:
    url: ssl://73d5ec93cbe843ab83b8f29e68f6979e.s1.eu.hivemq.cloud
  topic: hello
logging:
  level:
    org:
      springframework:
        mqtt: DEBUG
    com:
      genoyves: DEBUG


app:
  heartbeat:
    interval: 30000
    timeout: 60000
  max-concurrent-trips: 2000
  max-cars: 3000
  max-bookings-per-trip: 60
server:
  port: 5090