package com.gocavgo.delivary.enums.notification;

public enum NoticeEventType {
    PACKAGE_CREATED,
    PACKAGE_ACCEPTED,
    PACKAGE_PICKED_UP,
    PACKAGE_IN_TRANSIT,
    PACKAGE_DELIVERY_INITIATED,
    PACKAGE_DELIVERED,
    PACKAGE_COMPLETED,
    PACKAGE_CANCELLED,
    PACKAGE_ORIGIN_OFFICE,
    PACKAGE_ASSIGNED_DRIVER,
    PACKAGE_DESTINATION_OFFICE,
    PACKAGE_READY_FOR_COLLECTION,
    PACKAGE_CUSTODIAN_ASSIGNED,
    PACKAGE_CUSTODIAN_REMOVED,
    PACKAGE_CUSTODY_TRANSFERRED,
    TRANSFER_PENDING,
    TRANSFER_REQUESTED,
    TRANSFER_DONE,
    TRANSFER_CANCELED,
    TRANSFER_PACKAGE_ADDED
}
